-- Resume Files テーブル
CREATE TABLE resume_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,                             -- ファイルのタイトル
  user_name TEXT DEFAULT 'ゲストユーザー',          -- アップロードしたユーザー名
  status TEXT DEFAULT '添削済み',                  -- ファイルの状態
  file_path TEXT NOT NULL,                        -- ファイルのパス
  original_text TEXT,                             -- 元のテキスト
  corrected_text TEXT,                            -- 添削後のテキスト
  uploaded_at TIMESTAMPTZ DEFAULT NOW(),          -- アップロード日時
  metadata JSONB DEFAULT '{}'::JSONB              -- その他のメタデータ
);

-- Resume Files テーブルのセキュリティ設定
ALTER TABLE resume_files ENABLE ROW LEVEL SECURITY;

-- 参照を許可するポリシー（誰でも読み取り可能）
CREATE POLICY "Allow public read from resume_files"
ON resume_files
FOR SELECT
TO public
USING (true);

-- 挿入を許可するポリシー（誰でも追加可能）
CREATE POLICY "Allow public insert to resume_files"
ON resume_files
FOR INSERT
TO public
WITH CHECK (true);