-- Resume Files テーブル
CREATE TABLE resume_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  user_name TEXT DEFAULT 'ゲストユーザー',
  status TEXT DEFAULT '添削済み',
  file_path TEXT NOT NULL,
  uploaded_at TIMESTAMPTZ DEFAULT NOW(),
  metadata JSONB DEFAULT '{}'::JSONB
);

-- Resume Files テーブルに対するRLSポリシー
-- 匿名ユーザーでもアクセス可能なポリシー
ALTER TABLE resume_files ENABLE ROW LEVEL SECURITY;
ADD COLUMN original_text TEXT,
ADD COLUMN corrected_text TEXT;
-- 参照を許可するポリシー
CREATE POLICY "Allow public read from resume_files"
ON resume_files
FOR SELECT
TO public
USING (true);

-- 挿入を許可するポリシー
CREATE POLICY "Allow public insert to resume_files"
ON resume_files
FOR INSERT
TO public
WITH CHECK (true);

-- Keywords テーブル
CREATE TABLE keywords (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  keyword TEXT NOT NULL,
  action TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Keywords テーブルに対するRLSポリシー
ALTER TABLE keywords ENABLE ROW LEVEL SECURITY;

-- 参照を許可するポリシー
CREATE POLICY "Allow public read from keywords"
ON keywords
FOR SELECT
TO public
USING (true);

-- 挿入と更新を許可するポリシー
CREATE POLICY "Allow public insert and update to keywords"
ON keywords
FOR ALL
TO public
USING (true)
WITH CHECK (true);

-- ストレージバケットの作成
-- Note: これはSQL経由では実行できないので、Supabaseダッシュボードから作成する必要があります
-- Storage > Create bucket で「resume_files」という名前のバケットを作成

/*
ストレージバケットのRLSポリシー:
1. ダッシュボードのStorage > Policies から設定
2. 以下のポリシーを追加:
   - バケット名: resume_files
   - ポリシー名: Allow public read from resume_files
   - 許可する操作: SELECT
   - 対象: public
   - ポリシー: bucket_id = 'resume_files'
   
   - バケット名: resume_files
   - ポリシー名: Allow public upload to resume_files
   - 許可する操作: INSERT
   - 対象: public
   - ポリシー: bucket_id = 'resume_files'
*/