-- Keywords テーブル - 添削から除外すべきキーワードを管理
CREATE TABLE keywords (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  keyword TEXT NOT NULL,                          -- 制限キーワード
  action TEXT NOT NULL,                           -- キーワードに対するアクション（添削対象外/要確認/警告表示）
  created_at TIMESTAMPTZ DEFAULT NOW()            -- 作成日時
);

-- Keywords テーブルのセキュリティ設定
ALTER TABLE keywords ENABLE ROW LEVEL SECURITY;

-- 参照を許可するポリシー（誰でも読み取り可能）
CREATE POLICY "Allow public read from keywords"
ON keywords
FOR SELECT
TO public
USING (true);

-- 挿入と更新を許可するポリシー（誰でも追加・更新可能）
CREATE POLICY "Allow public insert and update to keywords"
ON keywords
FOR ALL
TO public
USING (true)
WITH CHECK (true);

-- 初期キーワードの登録
INSERT INTO keywords (keyword, action)
VALUES
    ('機密情報', '添削対象外'),
    ('個人情報', '添削対象外'),
    ('社内', '要確認');